# PROFILE DE TESTE - Configurado para ser ativado com @ActiveProfiles("test")

#PORT
server.port=8081

# PATH APPLICATION
server.servlet.context-path=/api-vaga

# CONFIG DATABASE PARA AMBIENTE DE TESTE
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.properties.hibernate.format_sql=true

#CONTROLA E EXECUTA SCRIPTS DO DB NO MOMENTO DA INICIALIZACAO DA APLICACAO
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# CORS FRONT END
client.cors.url=http://localhost:4200

# TOKENS E REFRESH TOKEN
vagarws.authenticator.token.cookie-name=access_token
vagarws.authenticator.token.cookie-refresh-token=refresh_token
vagarws.authenticator.token.secret=ZmluYW5jZTo6YWNhZGVtaWE=
vagarws.authenticator.token.expiration=2
vagarws.authenticator.token.refresh.expiration=7

# RESOURCE PROJECT - BANNER
vagarws.description=@project.name@
vagarws.version=@project.version@

# RESPONSAVEL EM SERIALIZAR NOS TESTE O OBJECT_MAPPER NO REGISTRO DE MODULO
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=UTC